# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1254, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.video_window = QtWidgets.QLabel(self.centralwidget)
        self.video_window.setGeometry(QtCore.QRect(30, 50, 640, 480))
        self.video_window.setScaledContents(True)
        self.video_window.setObjectName("video_window")
        self.btn_forward = QtWidgets.QPushButton(self.centralwidget)
        self.btn_forward.setGeometry(QtCore.QRect(150, 570, 75, 23))
        self.btn_forward.setObjectName("btn_forward")
        self.btn_left = QtWidgets.QPushButton(self.centralwidget)
        self.btn_left.setGeometry(QtCore.QRect(60, 610, 75, 23))
        self.btn_left.setObjectName("btn_left")
        self.btn_back = QtWidgets.QPushButton(self.centralwidget)
        self.btn_back.setGeometry(QtCore.QRect(150, 650, 75, 23))
        self.btn_back.setObjectName("btn_back")
        self.btn_right = QtWidgets.QPushButton(self.centralwidget)
        self.btn_right.setGeometry(QtCore.QRect(250, 610, 75, 23))
        self.btn_right.setObjectName("btn_right")
        self.btn_stop = QtWidgets.QPushButton(self.centralwidget)
        self.btn_stop.setGeometry(QtCore.QRect(150, 610, 75, 23))
        self.btn_stop.setObjectName("btn_stop")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1254, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.video_window.setText(_translate("MainWindow", "video_window"))
        self.btn_forward.setText(_translate("MainWindow", "前进"))
        self.btn_left.setText(_translate("MainWindow", "左转"))
        self.btn_back.setText(_translate("MainWindow", "后退"))
        self.btn_right.setText(_translate("MainWindow", "右转"))
        self.btn_stop.setText(_translate("MainWindow", "停止"))
